version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  versioning-strategy: widen
  open-pull-requests-limit: 10
  labels:
      - "automerge"
      - "dependencies"
